### ISSUE TITLE
Contribution: extending SIMDE usage to cover more architectures

### ISSUE THREAD

**Issue by mr-c** [BenLangmead/bowtie2#271]
Hello,

As part of updating the bowtie2 package for Debian I extended the SIMDE work by @junaruga for more platforms.

Results are looking good for 64-bit platforms: https://buildd.debian.org/status/package.php?p=bowtie2

(though s390x, which is 64 bit, has an some interesting test failures: https://buildd.debian.org/status/fetch.php?pkg=bowtie2&arch=s390x&ver=2.3.5.1-6&stamp=1576774666&raw=0 )

This issue to is gauge interest in adapting the Debian SIMDE patches for inclusion with bowtie2 itself. It will take a bit of work, as they are a bit Debian specific at the moment.

- Our Makefile: https://salsa.debian.org/med-team/bowtie2/blob/master/debian/rules
- Patch to simplify compiler flags: https://salsa.debian.org/med-team/bowtie2/blob/master/debian/patches/correct_64bit_test (Is `-m64` really needed on 64bit systems?)
- A small patch to the build system to pass the standard `CPPFLAGS` and `CFLAGS` (could be applied without modification): https://salsa.debian.org/med-team/bowtie2/blob/master/debian/patches/hardening.patch
- Enabling SIMD Everywhere using the an updated copy of https://github.com/nemequ/simde/commits/master: https://salsa.debian.org/med-team/bowtie2/blob/master/debian/patches/simde

Options for full inclusion of SIMDE:
1. Keep the `SIMDE_ENABLE_NATIVE_ALIASES` hack from the Debian patch
2. Do a one time prefixing of `simde` to all SIMD intrinsic types and function calls (safer)

Related issues: #46 #97 #236 

Thoughts from the maintainers and other contributors?

**Comment by junaruga** [comment]
> As part of updating the bowtie2 package for Debian I extended the SIMDE work by @junaruga for more platforms.

I contributed the SIMDE work to this bowtie2 repository in the past.
But to be fair, the instruction for the patch came from @achacond 's past work.

I am glad to see bowtie2 is used for more platforms.

**Comment by junaruga** [comment]
> though s390x, which is 64 bit, has an some interesting test failures

The CPU architecture s390x is big-endian unlike other 64-bit CPU architectures (little-endian) on Debian. It might be a big-endian specific issue?

Dear maintainers, for your information. Travis has s390x environment (`arch: s390x`)too.
https://docs.travis-ci.com/user/multi-cpu-architectures

**Comment by ch4rr0** [comment]
@mr-c, thank you for your contribution. We are currently wrapping changes for a new release and most likely would not be able to get these changes completed in time. In any event I will keep you updated on our timelines for this.

**Comment by mr-c** [comment]
@ch4rr0 Thanks for the response. Do let me know how I can be of assistance!

**Comment by ch4rr0** [comment]
@junaruga -- I am seeing some issues with the arm64 builds when using the new travis config. Any idea what could be causing the build failures?

https://travis-ci.org/BenLangmead/bowtie2/jobs/634282745?utm_medium=notification&utm_source=slack

**Comment by junaruga** [comment]
@ch4rr0 yes, I have an idea. You need to merge the commit: https://github.com/BenLangmead/bowtie2/commit/c6a6648fcd05bff0e5ca64a305bb1c488beacbcf (aligner_sw.h and sse_util.h) on master branch to bug_fixes at least.

My comment on https://github.com/BenLangmead/bowtie2/issues/207#issuecomment-570823094 meant it.

> To run aarch64 case with new way arch: arm64, you need to merge the commits c6a6648 and 2df34de to bug_fixes branch.

Why you do not rebase current bug_fixes on the latest master branch?
Here is the possible steps.

```
$ git branch
* bug_fixes
  master

$ git branch -m bug_fixes_old

$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

$ git pull
Already up to date.

$ git checkout -b bug_fixes
Switched to a new branch 'bug_fixes'
```

Cherry pick fixing the conflicts.
It might be good to do squash in bug_fixes branch's new commits by `git rebase -i <commit>` in advance.

```
$ git cherry-pick <your bug_fixes_old branch's commit A>
$ git cherry-pick <your bug_fixes_old branch's commit B>
...
```

Then push forcibly.

```
$ git push origin bug_fixes -f
```

**Comment by ch4rr0** [comment]
Ah, I had forgotten that the changes were only on the master branch. You're right I should have rebased `bug_fixes` onto master to consolidate all commits. I will keep that in mind moving forward. Thank you for your assistance!

**Comment by ch4rr0** [comment]
I merged master in bug_fixes so need to cherry pick the necessary commits.

**Comment by junaruga** [comment]
I have a good news. I am happy to assist.

Based on the latest `bug_fixes` branch and seeing the latest Travis CI result, I worked for my forked repository `git@github.com:junaruga/bowtie2.git` `bug_fixes_jaruga` branch.

Then 
* osx case: I was able to pass the "osx" case
* s390x and ppc64le cases: I was able to pass the build (`make allall`) adapting simde to the cases. Now some tests (not all the tests) are failed.

You can check [the commits and commit messages](https://github.com/junaruga/bowtie2/commits/bug_fixes_jaruga) and [the Travis CI result](https://travis-ci.org/junaruga/bowtie2/builds/635527166).

So, let me explain the total new 6 commits. Of course, adapting the commits is up to you.

1. Extend bug_fixes branches in the case working on forked repository.
  This is helpful to run Travis on multiple branches on a forked repository. Because `bug_fixes`.

  ```
  -    - bug_fixes
  +    - /^bug_fixes.*/
  ```

  Because `bug_fixes` branch is used for the origin (this repository)'s `bug_fixes` branch.

  ```
  $ git remote -v
  junaruga	git@github.com:junaruga/bowtie2.git (fetch)
  junaruga	git@github.com:junaruga/bowtie2.git (push)
  origin	git@github.com:BenLangmead/bowtie2.git (fetch)
  origin	git@github.com:BenLangmead/bowtie2.git (push)
  ```

2. Replace a tab or 2 spaces indent to 8 spaces indent.
  This is what I shared ch4rr0 today related to your commit. Total 3 lines. Enabling visualized tab on your editor is useful to find this kind of issue.

3. Fix Travis osx case.
  This is the commit to pass the osx case. In this commit, `python --version` is also replaced with `python3 --version` in `.travis.yml`.
  Installing `tbb`, that depends on `python` brew package by Travis's homebrew syntax, does not work. Because a `brew unlink python@2` is needed to be executed before that.

4. Fix `alphabet.app` and `alphabet.h` to fix the warnings on s390x and arm64.
  I saw the error on "bowtie" (not "bowtie2") s390x case (https://github.com/BenLangmead/bowtie/pull/102). But for "bowtie2", it was just warning. This commit is not required to pass the cases. 2 files (`alphabet.app` and `alphabet.h`).

5. Use simde on s390x and ppc64le cases.
  I was able to apply simde to s390x and ppc64le too. I am not sure that s390x and ppc64le has SIMD.
  * Add macros to support s390x and PowerPC.
    See https://wiki.debian.org/ArchitectureSpecificsMemo
  * Remove unused -DWITH_AARCH64 flag for aarch64 case.

6. Update for AddressSanitizer on s390x and ppc64le.
  This was necessary to pass the `make allall`. See the commit message for detail.

Thank you.

**Comment by ch4rr0** [comment]
Thank you for putting this together. I will take a look at the commits tomorrow. I posted some changes on bug_fixes to support SIMD on ppc64le by wrapping the altivec primitives. It seems to have compiled on was able to run some of our simple tests. Feedback on the changes is appreciated.

**Comment by junaruga** [comment]
> I posted some changes on bug_fixes to support SIMD on ppc64le by wrapping the altivec primitives. It seems to have compiled on was able to run some of our simple tests. Feedback on the changes is appreciated.

I am seeing the latest `bug_fixes` branch.
Let me give you some feedback about your commit "Add SSE wrappers for PowerPC".
It seems that you are implementing that a specific feature of the IBM cpu specific vector extension by yourself with downloading `third_party/vec128int.h`.

I think it's hard. When we need to add new 64-bit architecture such as `ppc64` (not `ppc64le` but the big endian version) and `riscv64` or we want to use not only SSE2 but also SSE3, SSE4, do you want to implement it by yourself?
Do you regularly want to check the latest version  of `third_party/vec128int.h` file, and adapt it?
I think the situation is hard.

I showed you the code using simde for `ppc64le` and `s390x` by checking `#if defined(__foo__)`, but it's not the best way, seeing @mr-c 's [patch file to use the simde for multiple CPU architectures](https://salsa.debian.org/med-team/bowtie2/blob/master/debian/patches/simde). Possibly we do not need to manage the CPU architecture specific code in `bowte2`, using `#define SIMDE_ENABLE_NATIVE_ALIASES` tip.

Possibly that's what he mentioned above.

If we use simde commonly for multiple CPU architectures and when we find the issue, just reporting it to [simde community](https://github.com/nemequ/simde) or sending the pull-request makes the maintenance easier. Because in the community, there are people using the vector extension for multiple CPU architectures like us. And contributing something to simde also helps other projects or biotools using SIMD.

**Comment by junaruga** [comment]
@mr-c I am trying your introduced `SIMDE_ENABLE_NATIVE_ALIASES` hack, on my forked branch: 
[bug_fixes_jaruga2](https://github.com/junaruga/bowtie2/tree/bug_fixes_jaruga2) for arm64, s390x and ppx64le cases with simplified [sse_wrap.h](https://github.com/junaruga/bowtie2/blob/bug_fixes_jaruga2/sse_wrap.h).

I am setting `-DSIMDE_ENABLE_OPENMP -fopenmp-simd` in `Makefile` [here](https://github.com/junaruga/bowtie2/blob/bug_fixes_jaruga2/Makefile#L205).

But I am seeing following errors in the [Travis log](https://travis-ci.org/junaruga/bowtie2/jobs/635741188).

```
aligner_swsse_loc_i16.cpp:2273:0: error: unterminated argument list invoking macro "SIMDE__M128I_TO_NATIVE"
 }
 ^
```

Do you have any idea to fix it?
Thank you.

**Comment by junaruga** [comment]
When I was reading the document about `SIMDE_ENABLE_NATIVE_ALIASES`, I found a notable sentence. I interpreted when it was defined in a patch in Debian's building system, that was okay. Because every time the deb package maintainer can check if the build is succeeded.
But when defining `SIMDE_ENABLE_NATIVE_ALIASES` could be not recommended.

https://github.com/nemequ/simde
> If you define SIMDE_ENABLE_NATIVE_ALIASES before including SIMDe you can use the same names as the native functions. Unfortunately, this is somewhat error-prone due to portability issues in the APIs, so it's recommended to only do this for testing.

**Comment by ch4rr0** [comment]
@junaruga -- I incorporated the SIMDE suggestions that you made earlier and got rid of the vec128int.h header.

**Comment by mr-c** [comment]
@junaruga In the other applications I've adapted I directly use SIMDE and don't use the `SIMDE_ENABLE_NATIVE_ALIASE` trick, so I'm not surprised it gave you issues.

**Comment by ch4rr0** [comment]
@mr-c -- I see some overlap between the work you've done on debian and @junaruga's work with SIMDE. Are there any additional changes you would like me to include before finalizing this release?

I got rid of `-m64` flag in the Makefile btw.

**Comment by junaruga** [comment]
@ch4rr0 Alright. Thank you for considering it.
@mr-c Thank you for reporting the situation on Debian.

> I see some overlap between the work you've done on debian and @junaruga's work with SIMDE. Are there any additional changes you would like me to include before finalizing this release?

I was working for my forked repository's `bug_fixes_jaruga3` branch.
And what I want to suggest for the additional changes is to apply folllowing commit for `Makefile` and `sse_wrap.h`.

https://github.com/junaruga/bowtie2/commit/50ca2535d8cdfae97e0c8efc597ddae9306391f2

It has 2 points.

`Makefile`

This is a refactoring for more compact logic than current implementation in `Makefile`.

```
ifeq ($(UNAME_ARCH),$(filter $(UNAME_ARCH),x86_64 amd64))
        BITS := 64
else ifeq ($(UNAME_ARCH),$(filter $(UNAME_ARCH),aarch64 s390x ppc64le))
        BITS := 64
        SSE_FLAG :=
        CXXFLAGS += -fopenmp-simd -DWITH_SIMDE
        CPPFLAGS += -Ithird_party/simde
endif
```

`sse_wrap.h`

Using `-DWITH_SIMDE` instead of `defined(__aarch64__) || defined(__s390x__) || defined(__powerpc__)` in `sse_wrap.h`.
The reason is to give opportunity to build on other 64-bit CPU architectures such as `ppc64` and `riscv64` easily. I see some other 64-bit architectures are build target on Debian.
This change relatively makes @mr-c apply the patch in Debian.

```
#ifdef WITH_SIMDE
#include "simde/x86/sse2.h"
#else
#include <emmintrin.h>
#endif

...

#ifdef WITH_SIMDE
typedef simde__m128i __m128i;
...
#define _mm_xor_si128(x, y) simde_mm_xor_si128(x, y)
#endif
```

**Comment by junaruga** [comment]
I think current `bug_fixes` branch's following code causes `sse_wrap.h:31:28: fatal error: simde/x86/sse2.h: No such file or directory` on `aarch64`, `s390x` and `ppc64le`.
`

```
CPPFLAGS += -Ithird_party
```

The lines could be like this.

```
CPPFLAGS += -Ithird_party/simde
```

**Comment by ch4rr0** [comment]
Fixed

**Comment by junaruga** [comment]
Thank you.

**Comment by cftarnas** [comment]
I'm attempting to compile on a RHEL 7.6 PPC box, and running into compile issues:
`(base) [cft@edx1 bowtie2-2.4.1]$ make 
g++ -O3  -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3  -funroll-loops -g3 -fopenmp-simd\"" -fopenmp-simd \
        -fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"\"" -DBUILD_TIME="\"`date -u`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DNDEBUG -Wall \
        -I third_party -Ithird_party/simde \
        -o bowtie2-build-s bt2_build.cpp \
        ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp diff_sample.cpp bowtie_build_main.cpp \
         -lz -lpthread -ltbb -ltbbmalloc_proxy
g++: error: unrecognized command line option ‘-fopenmp-simd’
make: *** [bowtie2-build-s] Error 1
`
Thank you

**Comment by junaruga** [comment]
> I'm attempting to compile on a RHEL 7.6 PPC box, and running into compile issues:
> ...
> g++: error: unrecognized command line option ‘-fopenmp-simd’

@cftarnas for non x86-64 (and amd64) CPU architecture, bowtie2 will use simde (`third_party/simde`) to build it. `simde` is registered as Git's submodule.

To install `simde`, you can try this commands.

Check current status.

```
$ git submodule
```

Install simde.

```
$ git submodule update --init --recursive
```

Check the status after the installation.

```
$ git submodule
```

Here is the CI case for `ppc64le`.

https://github.com/BenLangmead/bowtie2/blob/b8c13c0401885873a99b229fca668deecde08749/.travis.yml#L73-L78

```
$ POPCNT_CAPABILITY=0 NO_TBB=1 make
```

If you want to build with `tbb`, you need to install tbb by `yum install tbb-devel`, then

```
$ POPCNT_CAPABILITY=0 make
```

I am not sure we can build bowtie2 without `POPCNT_CAPABILITY=0` on ppc64le.

**Comment by junaruga** [comment]
> I'm attempting to compile on a RHEL 7.6 PPC box, and running into compile issues:

Could you share the result of `uname -a`? Is the PPC box "PPC little-endian (ppc64le)"? or "PPC big-endian"?

**Comment by cftarnas** [comment]
Thank you,

It's a little endian. uname -a output: 

`Linux xxx.xxx.com 4.14.0-115.18.1.el7a.ppc64le #1 SMP Wed Jan 29 11:49:09 EST 2020 ppc64le ppc64le ppc64le GNU/Linux`

**Comment by junaruga** [comment]
Okay. So, as bowtie2 `Makefile` considers `ppc64le`, you can build it.

**Comment by cftarnas** [comment]
Thank you for the help, running 
```
$ POPCNT_CAPABILITY=0 NO_TBB=1 make

```
was successful. We also had to change `-fopenmp-simd` to `-fopenmp`. The flag `-fopenmp-simd` does not exist for g++ (GCC) 4.8.5. 
As a side not we do have `tbb-devel.ppc64le` installed but the build still fails with `NO_TBB=0`.

Make test fails with Perl/cpan errors:
```
$ make test
if [ ! -d "/data/src/bowtie2/.tmp" ]; then \
        mkdir -p /data/src/bowtie2/.tmp/include /data/src/bowtie2/.tmp/lib ; \
fi
DL=$( ( which wget >/dev/null 2>&1 && echo "wget --no-check-certificate -O-" ) || echo "curl -L") ; \
$DL http://cpanmin.us | perl - -l /data/src/bowtie2/.tmp App::cpanminus local::lib ; \
eval `perl -I /data/src/bowtie2/.tmp/lib/perl5 -Mlocal::lib=/data/src/bowtie2/.tmp` ; \
/data/src/bowtie2/.tmp/bin/cpanm --force File::Which Math::Random Clone Test::Deep Sys::Info ; \

--2020-04-16 13:28:50--  http://cpanmin.us/
Resolving cpanmin.us (cpanmin.us)... 151.101.130.217, 151.101.66.217, 151.101.2.217, ...
Connecting to cpanmin.us (cpanmin.us)|151.101.130.217|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 302780 (296K) [text/plain]
Saving to: ‘STDOUT’

100%[=====================================================================================>] 302,780     1.14MB/s   in 0.3s   

2020-04-16 13:28:50 (1.14 MB/s) - written to stdout [302780/302780]

--> Working on App::cpanminus
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz ... OK
==> Found dependencies: ExtUtils::MakeMaker
--> Working on ExtUtils::MakeMaker
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.44.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.44 ... OK
Can't locate ExtUtils/Manifest.pm in @INC (@INC contains: FatPacked::634207608=HASH(0x25cd3d78) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at - line 132.
Can't locate local/lib.pm in @INC (@INC contains: /data/src/bowtie2/.tmp/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
/bin/sh: line 3: /data/src/bowtie2/.tmp/bin/cpanm: No such file or directory
make: *** [perl-deps] Error 127
```
We are looking into that now.

**Comment by junaruga** [comment]
@cftarnas maybe your environment does not have the perl libraries (`ExtUtils/Manifest.pm` and `local/lib.pm`).

You can install like this.

```
yum install perl(lib) perl(ExtUtils::Manifest)
```

or

```
yum install perl(lib) perl-ExtUtils-Manifest
```

By the way, bowtie2 RPM package is in review status yesterday [here](https://bugzilla.redhat.com/show_bug.cgi?id=1824348). You might be able to pick up the bowtie2 binary RPM ppc64le version built on Fedora rawhide (33) environment from [the page](https://koji.fedoraproject.org/koji/taskinfo?taskID=43448972). This page is not permanent link.

After passing the review, I try to build bowtie2 on EPEL7 ppc64le environment that you can certainly use on your environment.

**Comment by junaruga** [comment]
> After passing the review, I try to build it to the binary RPM and ship bowtie2 for EPEL7 ppc64le environment that you can certainly use on your environment.

Note bowtie2 RPM is available on EPEL 8 (x86_64,  ppc64le, aarch64), and EPEL 7 (x86_64,  ppc64le). See https://src.fedoraproject.org/rpms/bowtie2 .

**Comment by mr-c** [comment]
Given that bowtie2 has been using SIMDe for a few releases and that binary packages are available from RedHat and Debian, I am going to close this issue. Thanks all!

**Comment by mmokrejs** [comment]
Just out of curiosity I looked how `2.4.2` builds on Gentoo Linux on `x86_64` platform oa `AVX2` cpu host. The changes landed in `2.4.0` already.

```
$ objdump -d /usr/bin/bowtie2-align-s | grep vinsert -c
10
$ objdump -d /usr/bin/bowtie2-align-s | grep ymm -c
1964
$ objdump -d /usr/bin/bowtie2-align-s | grep xmm -c
8305
$ objdump -d /usr/bin/bowtie2-align-s | grep pcmpgt -c
21
$ objdump -d /usr/bin/bowtie2-align-s | grep vpmov -c
174
$
```

http://linasm.sourceforge.net/docs/instructions/simd.php
