### ISSUE TITLE
Bowtie2-2.5.5 build error because of make-version?

### ISSUE THREAD

**Issue by brobr** [BenLangmead/bowtie2#522]
Hi, I just tried upgrading Bowtie2-2.5.4 to Bowtie2-2.5.5 on Slackware linux. On Slackware64-current the updated bowtie2 built but not on patched, stable Slackware64-15.0. It stops - when compiling in a virtual machine - on:

      ...
      bowtie_main.cpp: In function ‘void check_x86_64_v3(int, const char**)’:
      bowtie_main.cpp:39:50: error: parameter to builtin not valid: x86-64-v3
         39 |         if (__builtin_cpu_supports ("x86-64-v3") && (argc<126)) {
            |                                                  ^~
      bowtie_main.cpp:39:62: error: parameter to builtin not valid: x86-64-v3
         39 |         if (__builtin_cpu_supports ("x86-64-v3") && (argc<126)) {
            |                                                              ^
      bowtie_main.cpp:39:62: error: parameter to builtin not valid: x86-64-v3
      bowtie_main.cpp:56:1: error: parameter to builtin not valid: x86-64-v3
         56 | }
            | ^
      make: *** [Makefile:400: bowtie2-align-s] Error 1
      bash-5.1# 

Compiling the previous version, Bowtie2-2.5.4, gives no problem - I just tried again.

The main differences between 'current' and '15.0' is that current comes with `make-4.4.1` while 15.0 has `make-4.3`. The error referred to line 400 in the Makefile and one of the many changes in the Makefile for 2.5.5 vs 2.5.4 is in a section that relates to the error. Can this error be bypassed (say by using `cmake`, see below) or is it best to stick to  Bowtie2-2.5.4 on 15.0? 

In Makefile of 2.5.5

    ...
    # do we have a 256-bit variant of the executable?
    ENABLE_V256 := 0
    
    BITS := 32
    ARCH ?= $(shell uname -m)
    ifneq (,$(findstring $(ARCH), x86_64 amd64))
      BITS := 64
      SSE_FLAG := -msse2
      POPCNT_CAPABILITY ?= 1
      ifneq (0, $(SSE_AVX2))
        ENABLE_V256 := 1
        V256_FLAG := -march=x86-64-v3 -mtune=znver3 -faligned-new -DSSE_AVX2 -DPOPCNT_CAPABILITY
        # tell 128-bit version to check for v256 capability and use it, if found
        SSE_FLAG += -DENABLE_x86_64_v3
      endif
    else ifneq (,$(findstring $(ARCH), aarch64 arm64 s390x powerpc64 powerpc64le ppc64 ppc64le))
      BITS := 64
      SSE_FLAG :=
      CXXFLAGS += -fopenmp-simd
      CPPFLAGS += -Ithird_party
      POPCNT_CAPABILITY ?= 0
     ...

the error-section in Makefile of 2.5.5:

    bowtie2-align-s-sanitized bowtie2-align-s: bt2_search.cpp $(SEARCH_CPPS) $(SHARED_CPPS) $(HEADERS) $(SEARCH_FRAGMENTS)
	$(CXX) $(RELEASE_FLAGS) $(RELEASE_DEFS) $(CXXFLAGS) \
		$(DEFS) -DBOWTIE2 $(NOASSERT_FLAGS) \
		$(CPPFLAGS) $(SSE_FLAG) \
		-o $@ $< \
		$(SHARED_CPPS) $(SEARCH_CPPS_MAIN) \
		$(LDFLAGS) $(LDLIBS)

Same sections in Makefile of 2.5.4:

    ...
    BITS := 32
    ARCH ?= $(shell uname -m)
    ifneq (,$(findstring $(ARCH), x86_64 amd64))
      BITS := 64
      ifeq (1, $(SSE_AVX2))
    	SSE_FLAG := -mavx2 -faligned-new -DSSE_AVX2
      else
    	SSE_FLAG := -msse2
      endif
    
      POPCNT_CAPABILITY ?= 1
    else ifneq (,$(findstring $(ARCH), aarch64 arm64 s390x powerpc64 powerpc64le ppc64 ppc64le))
      BITS := 64
      SSE_FLAG :=
      CXXFLAGS += -fopenmp-simd
      CPPFLAGS += -Ithird_party
      POPCNT_CAPABILITY ?= 0
    ...

the 2.5.4 section that has changed in 2.5.5 and where the error referred to:

    bowtie2-align-s-sanitized bowtie2-align-s: bt2_search.cpp $(SEARCH_CPPS) $(SHARED_CPPS) $(HEADERS) $(SEARCH_FRAGMENTS)
	$(CXX) $(RELEASE_FLAGS) $(RELEASE_DEFS) $(CXXFLAGS) \
		$(DEFS) -DBOWTIE2 $(NOASSERT_FLAGS) \
		$(CPPFLAGS) \
		-o $@ $< \
		$(SHARED_CPPS) $(SEARCH_CPPS_MAIN) \
		$(LDFLAGS) $(LDLIBS)

The build-script I used was with `make`.  The manual advices to use make when compiling from source. 
Slackware64-current comes with `cmake-4.3.0` while 15.0 has `cmake-3..21.4`. There is an option to install cmake-3.30.5 in `15.0`. Does it make sense to use `cmake` instead of `make`? Bowtie2-2.5.5 has in CMakeLists.txt: `cmake_minimum_required(VERSION 3.5 FATAL_ERROR)` and Bowtie2-2.5.4 in CMakeLists.txt: `cmake_minimum_required(VERSION 3.1 FATAL_ERROR)`.

Full error stack after unpacking the source:

            g++ -O3 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -funroll-loops -g3 -std=c++11 -Wall -Wno-unused-but-set-variable -DPOPCNT_CAPABILITY -DNO_SPINLOCK -DWITH_QUEUELOCK=1 \"" -std=c++11 -Wall -Wno-unused-but-set-variable -DPOPCNT_CAPABILITY -DNO_SPINLOCK -DWITH_QUEUELOCK=1  \
            	-fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat BOWTIE2_VERSION`\"" -DBUILD_HOST="\"${HOSTNAME:-`hostname`}\"" -DBUILD_TIME="\"`date -u`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DNDEBUG  \
            	-I third_party \
            	-o bowtie2-build-s bt2_build.cpp \
            	ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_locks.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp diff_sample.cpp bowtie_build_main.cpp \
            	 -lpthread -lz -lrt 
            g++ -O3 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -funroll-loops -g3 -std=c++11 -Wall -Wno-unused-but-set-variable -DPOPCNT_CAPABILITY -DNO_SPINLOCK -DWITH_QUEUELOCK=1 \"" -std=c++11 -Wall -Wno-unused-but-set-variable -DPOPCNT_CAPABILITY -DNO_SPINLOCK -DWITH_QUEUELOCK=1  \
            	-fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat BOWTIE2_VERSION`\"" -DBUILD_HOST="\"${HOSTNAME:-`hostname`}\"" -DBUILD_TIME="\"`date -u`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DBOWTIE_64BIT_INDEX -DNDEBUG  \
            	-I third_party \
            	-o bowtie2-build-l bt2_build.cpp \
            	ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_locks.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp diff_sample.cpp bowtie_build_main.cpp \
            	 -lpthread -lz -lrt 
            g++ -O3 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -funroll-loops -g3 -std=c++11 -Wall -Wno-unused-but-set-variable -DPOPCNT_CAPABILITY -DNO_SPINLOCK -DWITH_QUEUELOCK=1\"" -std=c++11 -Wall -Wno-unused-but-set-variable -DPOPCNT_CAPABILITY -DNO_SPINLOCK -DWITH_QUEUELOCK=1 \
            	-fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat BOWTIE2_VERSION`\"" -DBUILD_HOST="\"${HOSTNAME:-`hostname`}\"" -DBUILD_TIME="\"`date -u`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DNDEBUG \
            	-I third_party -msse2 -DENABLE_x86_64_v3 \
            	-o bowtie2-align-s bt2_search.cpp \
            	ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_locks.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp qual.cpp pat.cpp sam.cpp read_qseq.cpp aligner_seed_policy.cpp aligner_seed.cpp aligner_seed2.cpp aligner_sw.cpp aligner_sw_driver.cpp aligner_cache.cpp aligner_result.cpp ref_coord.cpp mask.cpp pe.cpp aln_sink.cpp dp_framer.cpp scoring.cpp presets.cpp unique.cpp simple_func.cpp random_util.cpp aligner_bt.cpp sse_util.cpp aligner_swsse.cpp outq.cpp aligner_swsse_loc_i16.cpp aligner_swsse_ee_i16.cpp aligner_swsse_loc_u8.cpp aligner_swsse_ee_u8.cpp aligner_driver.cpp bowtie_main.cpp \
            	 -lpthread -lz -lrt 
            aligner_seed2.cpp: In member function ‘size_t Descent::recalcOutgoing(const Read&, const Scoring&, TAlScore, TAlScore, DescentRedundancyChecker&, EFactory<DescentPos>&, const EList<DescentRoot>&, const EList<DescentConfig>&, PerReadMetrics&)’:
            aligner_seed2.cpp:585:21: warning: ‘edge.DescentEdge::nex’ may be used uninitialized [-Wmaybe-uninitialized]
              585 |         DescentEdge edge;
                  |                     ^~~~
            aligner_sw_driver.cpp: In member function ‘int SwDriver::extendSeedsPaired(Read&, Read&, bool, bool, SeedResults&, const Ebwt&, const Ebwt*, const BitPairReference&, SwAligner&, SwAligner&, const Scoring&, const PairedEndPolicy&, int, int, int, TAlScore&, TAlScore&, int, int, bool, bool, size_t, bool, size_t, size_t, size_t, size_t, size_t, size_t, size_t, bool, bool, size_t, size_t, bool, int, bool, AlignmentCacheIface&, RandomSource&, WalkMetrics&, SwMetrics&, SwMetrics&, PerReadMetrics&, AlnSinkWrap*, bool, bool, bool, bool, bool&)’:
            aligner_sw_driver.cpp:1815:32: warning: unused variable ‘riter’ [-Wunused-variable]
             1815 |                         size_t riter = 0;
                  |                                ^~~~~
            bowtie_main.cpp: In function ‘void check_x86_64_v3(int, const char**)’:
            bowtie_main.cpp:39:50: error: parameter to builtin not valid: x86-64-v3
               39 |         if (__builtin_cpu_supports ("x86-64-v3") && (argc<126)) {
                  |                                                  ^~
            bowtie_main.cpp:39:62: error: parameter to builtin not valid: x86-64-v3
               39 |         if (__builtin_cpu_supports ("x86-64-v3") && (argc<126)) {
                  |                                                              ^
            bowtie_main.cpp:39:62: error: parameter to builtin not valid: x86-64-v3
            bowtie_main.cpp:56:1: error: parameter to builtin not valid: x86-64-v3
               56 | }
                  | ^
            make: *** [Makefile:400: bowtie2-align-s] Error 1

**Comment by brobr** [comment]
I get bowtie2 built with cmake but the ${LIBDIRSUFFIX} (64) is not used via -DLIB_SUFFIX=${LIBDIRSUFFIX} in:

    mkdir -p build
    cd build
      cmake \
        -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
        -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DLIB_SUFFIX=${LIBDIRSUFFIX} \
        -DCMAKE_BUILD_TYPE=Release ..
      make
      make install/strip DESTDIR=$PKG
    cd ..
    
    # Don't ship .la files:
    rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la

and end up with this warning (because the .la files (??) are in /usr/lib, not /usr/lib64)???

    WARNING: rpath found in ./usr/bin/bowtie2-align-s:   RPATH                /usr/lib

**Comment by brobr** [comment]
Removing     -DLIB_SUFFIX=${LIBDIRSUFFIX}  from the cmake still gives the RPATH warning

This did not change that:

    # Don't ship .la files:
    rm -f $PKG/{,usr/}lib/*.la

**Comment by niemasd** [comment]
I'm getting the same error when updating to Bowtie2 v2.5.5:

```
2026-05-30T16:13:24Z #6 759.9 bowtie_main.cpp:39:43: error: parameter to builtin not valid: x86-64-v3
2026-05-30T16:13:24Z #6 759.9    39 |  if (__builtin_cpu_supports ("x86-64-v3") && (argc<126)) {
2026-05-30T16:13:24Z #6 759.9       |                                           ^~
2026-05-30T16:13:24Z #6 759.9 bowtie_main.cpp:39:55: error: parameter to builtin not valid: x86-64-v3
2026-05-30T16:13:24Z #6 759.9    39 |  if (__builtin_cpu_supports ("x86-64-v3") && (argc<126)) {
2026-05-30T16:13:24Z #6 759.9       |                                                       ^
2026-05-30T16:13:24Z #6 759.9 bowtie_main.cpp:56:1: error: parameter to builtin not valid: x86-64-v3
2026-05-30T16:13:24Z #6 759.9    56 | }
2026-05-30T16:13:24Z #6 759.9       | ^
2026-05-30T16:13:24Z #6 760.0 make: *** [Makefile:400: bowtie2-align-s] Error 1
```

I wonder if it's possible to first check if `__builtin_cpu_supports` supports the `"x86-64-v3"` parameter value? E.g.

```cpp
// `CHECK_x86_64_V3_IS_SUPPORTED` is `true` if `__builtin_cpu_supports` supports "x86-64-v3"
if(CHECK_x86_64_V3_IS_SUPPORTED && __builtin_cpu_supports ("x86-64-v3") && (argc<126)) {
```

**Comment by ch4rr0** [comment]
I pushed a potential fix for this issue to the master branch. Can you please try and let me know whether it works?

**Comment by brobr** [comment]
Hi,

Sorry for the slow response but I had trouble with my
virtual-machine with slackware-15.0 where bowtie2-2.5.5 did not
build. After reinstalling and patching the whole lot everything seems to
work; 2.5.4 compiles with make; 2.5.5 does not (as before). 

With the patched master (downloaded yesterday) compilation went without
a hitch with make-4.3 on 15.0 and make-4.4 on current.

Hth

Rob
