### ISSUE TITLE
Building bowtie2-2.3.1 on Fedora 25

### ISSUE THREAD

**Issue by amphioxus** [BenLangmead/bowtie2#102]
I've tried running the bowtie2 binaries on a server running Fedora 25, but support for multi-threading seems to be broken. (Process hangs indefinitely when I use more than one thread for bowtie2.)

So I tried to build it from source (which had worked fine on an Ubuntu 16.04 machine I tried it on before), but I'm getting build errors.  First, it was complaining about some missing tbb header, which I fixed by installing the tbb-devel package (sudo dnf install tbb-devel). When I run 'make' now, I get a bunch of errors, mostly the following: 

```bash
In file included from bt2_idx.h:42:0,
                 from bt2_io.cpp:25:
blockwise_sa.h:178:7: error:   overriding ‘virtual InorderBlockwiseSA<S2bDnaString>::~InorderBlockwiseSA() noexcept’
 class InorderBlockwiseSA : public BlockwiseSA<TStr> {
```

And 2 instances of:

```bash
blockwise_sa.h:218:5: error: looser throw specifier for ‘KarkkainenBlockwiseSA<TStr>::~KarkkainenBlockwiseSA() noexcept (false) [with TStr = S2bDnaString]’
     ~KarkkainenBlockwiseSA()
     ^
```

Compiler version: g++ (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

(Edit: I also tried  ```make NO_TBB=1``` but that didn't work either.)

Can anyone point me in the right direction?  I'm guessing it all has to do with multi-threading libraries, but I'm at a complete loss about how to fix this. 

Many thanks,
Armin

**Comment by amphioxus** [comment]
Apologies. I didn't realize that there's a second page of "issues". So I missed #40 (https://github.com/BenLangmead/bowtie2/issues/40), which seems to be addressing exactly what I'm describing here.

**Comment by amphioxus** [comment]
Duplicate of #40
