### ISSUE TITLE
Doesn't compile on vanilla Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by xapple** [BenLangmead/bowtie2#163]
I followed the instructions and simply did:

    wget https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.3.1/bowtie2-2.3.3.1-source.zip
    unzip bowtie2-2.3.3.1-source.zip
    cd bowtie2-2.3.3.1/
    make

The result was:

    g++ -O3 -m64 -msse2 -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABI
    LITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1\"" -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELO
    CK=1 \
            -fno-strict-aliasing -DBOWTIE2_VERSION="\"`cat VERSION`\"" -DBUILD_HOST="\"`hostname`\"" -DBUILD_TIME="
    \"`date`\"" -DCOMPILER_VERSION="\"`g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_
    SOURCE  -DBOWTIE_MM  -DBOWTIE2 -DNDEBUG -Wall \
             -I third_party \
            -o bowtie2-build-s bt2_build.cpp \
            ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp bt2_io.cpp bt2_util.cpp reference
    .cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp diff_sample.cpp bowtie_build_main.cpp \
              -lz -lpthread -ltbb -ltbbmalloc_proxy
    In file included from bt2_idx.h:42:0,
                     from bt2_build.cpp:28:
    blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
    compilation terminated.
    In file included from ds.h:30:0,
                     from ref_read.h:33,
                     from ref_read.cpp:20:
    threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
    compilation terminated.
    In file included from ds.h:30:0,
                     from edit.h:29,
                     from edit.cpp:21:
    threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
    compilation terminated.
    In file included from bt2_idx.h:42:0,
                     from bt2_idx.cpp:25:
    blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
    compilation terminated.
    In file included from bt2_idx.h:42:0,
                     from bt2_io.cpp:25:
    blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
    compilation terminated.
    In file included from bt2_idx.h:42:0,
                     from bt2_util.cpp:26:
    blockwise_sa.h:24:21: fatal error: tbb/tbb.h: No such file or directory
    compilation terminated.
    In file included from ds.h:30:0,
                     from ref_read.h:33,
                     from reference.h:32,
                     from reference.cpp:22:
    threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
    compilation terminated.
    In file included from ds.h:30:0,
                     from ds.cpp:20:
    threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
    compilation terminated.
    In file included from ds.h:30:0,
                     from sequence_io.h:28,
                     from multikey_qsort.h:24,
                     from multikey_qsort.cpp:20:
    threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
    compilation terminated.
    In file included from ds.h:30:0,
                     from random_util.h:25,
                     from random_source.cpp:21:
    threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
    compilation terminated.
    In file included from diff_sample.cpp:20:0:
    diff_sample.h:24:21: fatal error: tbb/tbb.h: No such file or directory
    compilation terminated.
    In file included from ds.h:30:0,
                     from bowtie_build_main.cpp:25:
    threading.h:29:24: fatal error: tbb/mutex.h: No such file or directory
    compilation terminated.
    Makefile:283: recipe for target 'bowtie2-build-s' failed
    make: *** [bowtie2-build-s] Error 1

This seems pretty critical when your documentation states: "Building Bowtie 2 from source requires a GNU-like environment with GCC, GNU Make and other basics. It should be possible to build Bowtie 2 on most vanilla Linux installations".

**Comment by BenLangmead** [comment]
You are right that our documentation was no longer accurate.  I just committed changes to the documentation addressing this.

**Comment by xapple** [comment]
Are you telling me this is a feature not a bug ? So how do you compile the program ?

**Comment by BenLangmead** [comment]
If you don't have TBB library, then `make NO_TBB=1`
